### ISSUE TITLE
../editgraph is not working 

### ISSUE THREAD

**Issue by shivangvijay** [ControlCore-Project/concore#25]
Attaching the screenshot 
![Screenshot from 2023-01-07 16-53-49](https://user-images.githubusercontent.com/36565630/211147826-e614d2f1-59c5-4313-9097-d841db4ab4c3.png)

**Comment by amit-62** [comment]
`editgraph` opens controlcore-editor you can alternatively open it using this [link](http://controlcore-project.github.io/DHGWorkflow).
Try `getgraph` see if it work, don't forget to follow instruction guide.

**Comment by pradeeban** [comment]
Thanks @shivangvijay for pointing out this bug and the fix.

This is fixed in main and dev, crediting to you in the commit - https://github.com/ControlCore-Project/concore/commit/4e708b0a6ee6255ea7fc0b8d13568ffd802aa648

Please let us know if this problem still persists.

**Comment by shivangvijay** [comment]
Thanks, It's working now.

**Comment by pradeeban** [comment]
Thanks a lot, @shivangvijay, for all your contributions!
