### ISSUE TITLE
Output result gets overridden

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore#35]
Reproduce

1) run a study

Expected:
All Data generated , Should be present in the output files 

Actual:
Only last entry of result is present in the result files

Due to this line in the controller.py
https://github.com/ControlCore-Project/concore/blob/main/example/controller.py#L27
We Should generate controller.py in a way that it should append in the file not write

@pradeeban

**Comment by pradeeban** [comment]
Thanks for the report, @parteekcoder. But this is the expected behavior for the concore controller implementation. Every result updates the previous, and the last one is presented.

If you want to keep track of the progress, that should be a separate implementation.

**Comment by parteekcoder** [comment]
> Thanks for the report, @parteekcoder. But this is the expected behavior for the concore controller implementation. Every result updates the previous, and the last one is presented.
> 
> If you want to keep track of the progress, that should be a separate implementation.

ok I thought that result files are to store all output generated , no problem thanks for reviewing
