### ISSUE TITLE
getFilesList Should be more restrictive  (Suggestion)

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore#36]
This method return the all files we have in our project , Rather its functioning should be limited to some directories only

I Know it is open source project so the code is available on the github itself but Yet as a developer I think API should be more restrictive

**Comment by pradeeban** [comment]
getFilesList is in its early stage. How to actually use it in the integrated implementation is part of the GSoC. Currently, it is not really utilized.
